[package]
name = "tauri-plugin-better-posthog"
version = "0.0.0"
description = "Tauri plugin for PostHog analytics"
links = "tauri-plugin-better-posthog"
edition = { workspace = true }

[lints]
workspace = true

[build-dependencies]
tauri-plugin = { version = "2.5.2", features = ["build"] }

[dependencies]
tauri = "2.9.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
log = "0.4.29"
uuid = { version = "1.19.0", features = ["v4", "v7"] }
better-posthog = { path = "../better-posthog" }
