name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/actions/setup-node
      - name: Check code
        run: pnpm lint
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/actions/setup-rust
        with:
          stable-components: clippy
          nightly-components: rustfmt
      - name: Check formatting
        run: cargo +nightly fmt --check
      - name: Check linting
        run: cargo clippy --locked -- -D warnings
